Feature/create travel agent controller
Gesheft-Rves/travel-agency-service pull request #29
Opened 2019-04-03 07:16 UTC by aslanovr

2019-04-03 08:29 UTC, zor07 requested changes

2019-04-03 08:29 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/controller/TravelAgentController.java
> +    TravelAgentDTO travelAgent2DTO(TravelAgent travelAgent) {
Почему не приватный метод?

2019-04-03 08:29 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/controller/TravelAgentController.java
> +    TravelAgent dto2TravelAgent (TravelAgentDTO travelAgentDTO) {
Приватность

2019-04-03 08:29 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/entity/dto/TravelAgentDTO.java
> +@Builder @ToString
Зачем в дто столько ломбока?

2019-04-03 08:29 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/repository/impl/TravelAgentRepositoryImpl.java
> +        String query = "SELECT *, " +
Опять в скл где то капсом где то в нижнем регистре ключевые слова

2019-04-03 08:29 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/repository/impl/TravelAgentRepositoryImpl.java
> +        String query = "SELECT *, " +
Ключевые слова в разном регистре

2019-04-03 08:29 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/repository/impl/TravelAgentRepositoryImpl.java
> +    public List<TravelAgent> list() {
Тесты есть на новый метод репозитория?

2019-04-03 08:29 UTC, zor07 commented on src/main/resources/templates/travelAgent/form.html
> +                        <input type="number" step="0.1" placeholder="Введите лимит" class="form-control" th:field="*{limitAmount}" th:required="required"/>
Step неправильный. Этот атрибут равен минимальному значению на которое можно изменить значение поля. В деньгах это .01, т.е. копейка, в твоем случае 10 копеек

2019-04-03 08:29 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TravelAgentRepositoryImplTest.java
>      public void createTest() {
Есть тесь на метод list?

2019-04-04 11:42 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/repository/impl/TravelAgentRepositoryImpl.java
> +        String query = "SELECT *, " +
Исправил

2019-04-04 11:43 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/repository/impl/TravelAgentRepositoryImpl.java
> +        String query = "SELECT *, " +
исправил

2019-04-04 11:44 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/controller/TravelAgentController.java
> +    TravelAgentDTO travelAgent2DTO(TravelAgent travelAgent) {
иправил

2019-04-04 11:45 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/controller/TravelAgentController.java
> +    TravelAgent dto2TravelAgent (TravelAgentDTO travelAgentDTO) {
исправил

2019-04-04 14:45 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/entity/dto/TravelAgentDTO.java
> +@Builder @ToString
Максимум безболезненно можно убрать только toString, остальное используется в контроллере.

2019-04-04 14:45 UTC, aslanovr commented on src/main/resources/templates/travelAgent/form.html
> +                        <input type="number" step="0.1" placeholder="Введите лимит" class="form-control" th:field="*{limitAmount}" th:required="required"/>
поставил 0.01

2019-04-04 16:17 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/repository/impl/TravelAgentRepositoryImpl.java
> +    public List<TravelAgent> list() {
сделал

2019-04-04 16:17 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/TravelAgentRepositoryImplTest.java
>      public void createTest() {
сделал

2019-04-04 18:18 UTC, zor07 approved these changes

2019-04-05 16:22 UTC, merged