Feature/tour schedule controller
Gesheft-Rves/travel-agency-service pull request #46
Opened 2019-07-16 20:16 UTC by aslanovr

2019-07-19 09:58 UTC, zor07 requested changes

2019-07-19 09:58 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/controller/TourScheduleController.java
> +                .startingDateTime(LocalDateTime.parse(tourScheduleDTO.getStartingDateTime(), DateTimeFormatter.ISO_DATE_TIME))
`DateTimeFormatter.ISO_DATE_TIME` - кажется можно без этого аргумента

2019-07-19 09:58 UTC, zor07 commented on src/main/resources/templates/tourSchedule/card.html
> +                    <p class="form-control-static" th:text="${tourSchedule.getTransport()}"></p>
Здесь что отображается? ID Или как?

2019-07-19 09:58 UTC, zor07 commented on src/main/resources/templates/tourSchedule/card.html
> +    <h2 th:text="'Карточка тур-агента'"></h2>
Так что за карточка в итоге?

2019-07-19 09:58 UTC, zor07 commented on src/main/resources/templates/tourSchedule/form.html
> +    <h2 th:text="'Новый тур-агент'"></h2>
Новый кто? Мне кажется тут расписание туров все-таки

2019-07-20 12:51 UTC, aslanovr commented on src/main/resources/templates/tourSchedule/form.html
> +    <h2 th:text="'Новый тур-агент'"></h2>
таки ты прав, на радостях забыл про эти нюансы

2019-07-20 12:51 UTC, aslanovr commented on src/main/resources/templates/tourSchedule/card.html
> +    <h2 th:text="'Карточка тур-агента'"></h2>
исправил

2019-07-20 12:52 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/controller/TourScheduleController.java
> +                .startingDateTime(LocalDateTime.parse(tourScheduleDTO.getStartingDateTime(), DateTimeFormatter.ISO_DATE_TIME))
Делал по примеру из документации, глубоко не изучал. Попробую

2019-07-20 17:55 UTC, zor07 commented
👍

2019-07-20 17:55 UTC, zor07 approved these changes

2019-07-20 17:57 UTC, merged