Delete multilanguage and refactoring controllers and templates.
Gesheft-Rves/travel-agency-service pull request #48
Opened 2019-07-28 18:58 UTC by aslanovr

2019-07-31 17:25 UTC, zor07 requested changes

2019-07-31 17:25 UTC, zor07 commented on src/main/resources/templates/auth/register.html
> +    <h2 th:text="Регистра"></h2>
ция?

2019-07-31 17:25 UTC, zor07 commented on src/main/resources/templates/tour/list.html
> +    <a th:href="${'/tour/new'}"> Создать туров</a>
тур наверное

2019-07-31 17:27 UTC, zor07 commented on src/main/resources/templates/fragments/header.html
> +                     <li><a href="#" th:href="@{/logout}" th:text="logout"></a></li>
`th:text="logout"` тут нужно на русский перевести

2019-08-03 09:18 UTC, aslanovr commented on src/main/resources/templates/tour/list.html
> +    <a th:href="${'/tour/new'}"> Создать туров</a>
исправил

2019-08-03 09:18 UTC, aslanovr commented on src/main/resources/templates/auth/register.html
> +    <h2 th:text="Регистра"></h2>
исправил

2019-08-03 09:19 UTC, aslanovr commented on src/main/resources/templates/fragments/header.html
> +                     <li><a href="#" th:href="@{/logout}" th:text="logout"></a></li>
выйти

2019-08-03 09:22 UTC, merged