Spring Security and a bit of refactoring
Gesheft-Rves/travel-agency-service pull request #49
Opened 2019-07-29 16:32 UTC by Gesheft-Rves

1) Added Spring Security
2) Modified DB schema for security operation
3) Small renaming for AppUser web page
4) Removed unnecessary (unused/ unused classes and their derivatives)

2019-07-31 17:38 UTC, zor07 requested changes

2019-07-31 17:38 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/controller/UserController.java
> +    public void setUserService(UserService userService) {
Сервисы сделать финальными и автовайрить через конструктор

2019-07-31 17:38 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/entity/Role.java
> +    ROLE_SUPER,
Приставку ROLE убрать

2019-07-31 17:38 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/service/UserService.java
> +        for (User user : list()){
Сделать нормально используя возможности Spring JPA, добавить в репозитой метод `User findByLogin(String login)`, и в этом методе вместо перебора всех юзеров юзать этот метод

2019-07-31 17:38 UTC, zor07 commented on src/main/resources/templates/users/form.html
> +        <form class="form-horizontal" th:object="${user}" th:action="@{/users/save}" method="post">
На этой странице нужно задавать роль новому пользователю

2019-07-31 17:38 UTC, zor07 commented on src/main/resources/templates/users/list.html
> +<div th:if="${not #lists.isEmpty(userslist)}">
На этой странице нужно выводить роль пользователя

2019-07-31 17:38 UTC, zor07 commented on src/main/resources/templates/users/list.html
> +                    <li><a th:href="${'/users/delete/' + user.Id}" th:text="Удалить"></a> </li>
Id нужно начинать с маленькой буквы

2019-08-07 19:49 UTC, Gesheft-Rves commented on src/main/java/com/javastudents/travelagency/controller/UserController.java
> +    public void setUserService(UserService userService) {
Готово

2019-08-07 19:50 UTC, Gesheft-Rves commented on src/main/java/com/javastudents/travelagency/entity/Role.java
> +    ROLE_SUPER,
Без Role не будет работать для спринг секъюрити важна приставка

2019-08-07 19:50 UTC, Gesheft-Rves commented on src/main/java/com/javastudents/travelagency/service/UserService.java
> +        for (User user : list()){
Сделал

2019-08-07 19:50 UTC, Gesheft-Rves commented on src/main/resources/templates/users/form.html
> +        <form class="form-horizontal" th:object="${user}" th:action="@{/users/save}" method="post">
+

2019-08-07 19:51 UTC, Gesheft-Rves commented on src/main/resources/templates/users/list.html
> +<div th:if="${not #lists.isEmpty(userslist)}">
+

2019-08-08 12:07 UTC, zor07 approved these changes

2019-08-08 16:40 UTC, merged