Creating classes, interfaces, and tests for CRUD methods to work with the Database
Gesheft-Rves/travel-agency-service pull request #8
Opened 2018-12-26 18:22 UTC by Gesheft-Rves

2019-01-06 16:48 UTC, zor07 requested changes

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppPermissionRepositoryTest.java
> +    }
Где здесь проверяется обновление сущности?

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppRolePermissionRepositoryTest.java
> +        Assert.assertEquals(expected, appRolePermissionRepository.read(5).getAppRolePermissionId());
Что ты здесь проверяешь? Ты взял запись с id = 5 -  (appRolePermissionRepository.read(5)), а потом проверяешь что у неё id = 5 ? В чем смысл теста?

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppRolePermissionRepositoryTest.java
> +        Assert.assertNotNull(byId);
Здесь и так not null, иначе бы  byId.getAppRoleId() - выкинуло exception

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppRolePermissionRepositoryTest.java
> +        Assert.assertNotNull(newAppRolePermission);
Эта проверка не нужна, если нул то проверка ниже не пройдет

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppRolePermissionRepositoryTest.java
> +        Assert.assertEquals(appRolePermission.getAppRoleId(), newAppRolePermission.getAppRoleId());
Ты не проверяешь тут именно то что ты обновил значение.

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppRoleRepositoryTest.java
> +        Assert.assertNotNull(byId);
Убери это, тк проверка излишняя

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppRoleRepositoryTest.java
> +        Assert.assertNotNull(newAppRole);
Assert.assertNotNull(newAppRole) - имеет смысл, если ты потом не используешь далее нигде newAppRole. А раз используешь, то в случае если newAppRole - будет null у тебя будет ошибка и тест все равно не пройдет. Поэтому assertNotNull - перегружает просто код и не несет пользы. Убери во всех аналогичных случаях

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppRoleRepositoryTest.java
> +        Assert.assertEquals(appRole.getAppRoleId(), newAppRole.getAppRoleId());
```
AppRole appRole = repository.read(2);
AppRole newAppRole = repository.read(2);
Assert.assertEquals(appRole.getAppRoleId(), newAppRole.getAppRoleId());
```

Последняя строка равносильна: 

`Assert.assertEquals( repository.read(2).getAppRoleId(),  repository.read(2).getAppRoleId());`

надо бы нормально проверку организовать

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppUserRepositoryTest.java
> +        String expectedValue = "New appUser";
С апдейтами везде одна и та же проблема. Везде нужно переделать, выше указывал все замечания. Ниже уже к апдейтам не буду ничего писать. Их все надо переделать

2019-01-06 16:48 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/AppUserRoleRepositoryTest.java
> +        Assert.assertEquals(expected, repository.read(4).getAppUserRoleId());
repository.read(4) - здесь id будет 4, потому что ты берешь запись с таким id. Кажется немного странно это проверять. Плюс возможно там уже был id 4 в базе. Все аналогичные create тесты также надо переделать

2019-01-09 16:32 UTC, closed without merging

2019-01-15 16:36 UTC, Gesheft-Rves commented on src/test/java/com/javastudents/travelagency/repository/AppRolePermissionRepositoryTest.java
> +        Assert.assertEquals(expected, appRolePermissionRepository.read(5).getAppRolePermissionId());
ok

2019-01-15 16:38 UTC, Gesheft-Rves commented on src/test/java/com/javastudents/travelagency/repository/AppRolePermissionRepositoryTest.java
> +        Assert.assertNotNull(byId);
ok

2019-01-15 16:39 UTC, Gesheft-Rves commented on src/test/java/com/javastudents/travelagency/repository/AppRolePermissionRepositoryTest.java
> +        Assert.assertNotNull(newAppRolePermission);
ok

2019-01-15 16:40 UTC, Gesheft-Rves commented on src/test/java/com/javastudents/travelagency/repository/AppRolePermissionRepositoryTest.java
> +        Assert.assertEquals(appRolePermission.getAppRoleId(), newAppRolePermission.getAppRoleId());
ok

2019-01-15 16:40 UTC, Gesheft-Rves commented on src/test/java/com/javastudents/travelagency/repository/AppRoleRepositoryTest.java
> +        Assert.assertNotNull(byId);
ok

2019-01-15 16:42 UTC, Gesheft-Rves commented on src/test/java/com/javastudents/travelagency/repository/AppRoleRepositoryTest.java
> +        Assert.assertNotNull(newAppRole);
ok

2019-01-15 16:44 UTC, Gesheft-Rves commented on src/test/java/com/javastudents/travelagency/repository/AppRoleRepositoryTest.java
> +        Assert.assertEquals(appRole.getAppRoleId(), newAppRole.getAppRoleId());
ok

2019-01-15 16:45 UTC, Gesheft-Rves commented on src/test/java/com/javastudents/travelagency/repository/AppUserRepositoryTest.java
> +        String expectedValue = "New appUser";
ok

2019-01-15 16:47 UTC, Gesheft-Rves commented on src/test/java/com/javastudents/travelagency/repository/AppUserRoleRepositoryTest.java
> +        Assert.assertEquals(expected, repository.read(4).getAppUserRoleId());
ok