Testing/repository classes
Gesheft-Rves/travel-agency-service pull request #9
Opened 2019-01-04 14:52 UTC by aslanovr

2019-01-08 10:27 UTC, zor07 requested changes

2019-01-08 10:27 UTC, zor07 commented on src/main/java/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
Это что такое? Почему это попало в гит? Надо убрать, чтоб вообще ни одного файла идеи не попадало в гит. Будь внимательнее, уже второй раз

2019-01-08 10:27 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/entity/TravelAgent.java
> +    private boolean enabled;
Ты используешь классы обертки для примитивов. Если начал лучше это делать везде. Используй Boolean

2019-01-08 10:27 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/repository/impl/CustomerRepositoryImpl.java
> +    @Autowired
Это лишнее. В спринге есть несколько способов автовайрить бины. Можно здесь, можно через сеттер, а можно через конструктор. Как раз ниже ты уже автовайришь через конструктор.

2019-01-08 10:27 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/repository/impl/DepartmentRepositoryImpl.java
> +    @Autowired
Это тоже лишнее. Да и вообще, Customer и Department были черновыми классами и все равно их выпиливать

2019-01-08 10:27 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImpl.java
> +    @Autowired
Проследи чтобы у тебя везде автовайринг был только в одном месте. Лучше через конструктор. Проследи во всех остальных классах

2019-01-08 10:27 UTC, zor07 commented on src/main/java/com/javastudents/travelagency/service/impl/TravelAgentServiceImpl.java
> +public class TravelAgentServiceImpl implements TravelAgentService {
А почему тут методы не реализованы?

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/AbstractTest.java
> +   /* @Before
Такое не нужно коммитить. Удали из этого класса все что лишнее

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/CustomerRepositoryImplTest.java
> +        Assert.assertNotNull(byName);
Нот нул в этом случае лишний. Адаму такое много где писал

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/CustomerRepositoryImplTest.java
> +        Assert.assertNotEquals(customer.getName(), customerOld.getName());
Здесь лучше сравнить на равенство с конкретным значением, вместо сравнения на неравенство со старым объектом

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/CustomerRepositoryImplTest.java
> +        Assert.assertNotNull(customer);
Тебе тоже напишу. Если ты проверяешь что какой то объект не нулл, а потом используешь этот объект ниже, то проверка нотнул - лишняя, так как если объект нулл, в месте где ты его ниже используешь будет ошибка и тест не пройдет. Убери везде лишние нот нулы

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/CustomerRepositoryImplTest.java
> +        Assert.assertEquals(customerOld.getId(), customer.getId());
```
 Customer customerOld = repository.read(2)
 Customer customer = repository.read(2)
```
Кажется немного странно проверять что у двух объектов полученных одним и тем же способоб одинаковый айдишник

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/CustomerRepositoryImplTest.java
> +        String sql = "SELECT COUNT(*) FROM   customer WHERE department_id = 2";
Вообще немного странно что тесты кастомера у тебя не в отдельной ветке а вместе со всем идут. Адам сделал в отдельной. Я тебе забыл это сказать? В любом случае ладно. Все замечания по кастомеру фиксить не нужно, все равно это удалим. Он нужен был просто для тренировки

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/DepartmentRepositoryImplTest.java
> +public class DepartmentRepositoryImplTest extends AbstractTest implements CrudTest {
Чем тебя не устроило старое название?) Хорошо что написал. Надо бы везде избавиться от Impl в названии тестовых классов. Ты ведь в них не Impl классы автовайришь

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Integer tourScheduleIdExpected = 1;
можно было бы заюзать одну переменную expectedId = 1

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Purchase purchase = purchaseRepository.read(1);
Ниже, вместо того, чтобы юзать объект ты еще 3 раза залезешь в базу

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Assert.assertEquals(id, purchaseRepository.read(id).getId());
Это странная проверка которая с апдейт тестом тяжело соотносится

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Assert.assertEquals(id, purchaseRepository.read(id).getId());
Плюс про нот нул. Если бы объект был нул и без проверки выше в этом месте все бы сломалось

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Assert.assertNotEquals(test, purchaseRepository.read(1).getOperationDate());
Во всех апдейт тестах проверяй что ты реально поменял значение. Сейчас ты проверяшь что оно просто не равно тому что ты в какой то момент времени успел прочитать.

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Assert.assertNotEquals(test, purchaseRepository.read(1).getOperationDate());
Плюс переменная test - не очень удачное название. приходится идти выше и смотреть что это за тест такой

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +    public void updateTest() {
Ниже будут замечания, аналогичные ошибки уже встречал. Поправь все апдейт тесты которые имеют аналогичные проблемы

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Purchase transportSeat1 = purchaseRepository.read(id);
Purchase transportSeat1 - название переменной сильно сбивает с толку

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Purchase purchase = Purchase.builder()
Лучше добавить что то в бд через скрипт, а здесь просто удалить. Слишком много операций в тесте

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TourCategoryRepositoryImplTest.java
> +    }
Где ты проверяешь что апдейт сработал?

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TourCategoryRepositoryImplTest.java
> +        String sql = "SELECT name from tour_category where tour_category_id = (select max(tour_category_id) from tour_category)";
служебные слова либо все большими либо все маленькими лучше писать

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TourRepositoryImplTest.java
> +        String sql = "SELECT name from tour where tour_id = (select max(tour_id) from tour)";
Во всех запросах проследи чтобы была одинаковая стилистика. Либо все в апперкейсе либо в лоуер кейсе служебные скуль слова

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TourRepositoryImplTest.java
> +        String tourName = "Test delete";
Уже всетрачал подобное. Слишком много операций, лучше добавить через скрипт а потом удалить. Прочекай все методы deleteTest

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TourScheduleRepositoryImplTest.java
> +        Assert.assertEquals(timestamp, tourSchedule.getStartingDateTime());
Ты изменил объект и прочекал что объект изменился. Что там произошло в базе в тесте не проверяется

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TourScheduleRepositoryImplTest.java
> +        TourSchedule tourScheduleNew = TourSchedule.builder()
писал про делиты

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TransportRepositoryImplTest.java
> +    }
А что собственно поменяться должно было? Никак не проверяешь что в базе что то изменилось

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TransportRepositoryImplTest.java
> +        Transport transport = Transport.builder()
см про делиты

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TransportSeatRepositoryImplTest.java
> +        Assert.assertEquals(transportSeat.getId(), transportSeatNew.getId());
Проверь все апдейты. Не вижу чтоб ты проверял обновление

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TransportSeatRepositoryImplTest.java
> +        Assert.assertEquals(transportSeat.getId(), transportSeatNew.getId());
Я к тому, что если удалить   transportSeatRepository.update(transportSeat) - вот это, то тест пройдет. Проверь все методы, я мог упустить аналогичные ситуации. И дальше возможно специально уже не напишу, так как предупреждаю чекнуть все методы тут

2019-01-08 10:27 UTC, zor07 commented on src/test/java/com/javastudents/travelagency/repository/impl/TransportSeatRepositoryImplTest.java
> +        TransportSeat transportSeat = TransportSeat.builder()
см делиты

2019-01-12 17:06 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/TransportSeatRepositoryImplTest.java
> +        TransportSeat transportSeat = TransportSeat.builder()
исправил

2019-01-12 17:07 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/TransportSeatRepositoryImplTest.java
> +        Assert.assertEquals(transportSeat.getId(), transportSeatNew.getId());
Был косяк убрал, т.к. делал заглушку забыл доделать

2019-01-12 17:07 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/TransportRepositoryImplTest.java
> +    }
Иправил

2019-01-12 17:07 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/TransportRepositoryImplTest.java
> +        Transport transport = Transport.builder()
убрал лишнее

2019-01-12 17:08 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImpl.java
> +    @Autowired
тоже исправил

2019-01-12 17:08 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/entity/TravelAgent.java
> +    private boolean enabled;
переделал в Boolean

2019-01-15 16:36 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/AbstractTest.java
> +   /* @Before
убрал

2019-01-15 16:37 UTC, aslanovr commented on src/main/java/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
убрал

2019-01-15 16:37 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImpl.java
> +    @Autowired
переделал

2019-01-15 16:38 UTC, RAsLM commented on src/test/java/com/javastudents/travelagency/repository/impl/CustomerRepositoryImplTest.java
> +        Assert.assertNotNull(byName);
notNull везде где не нужно выпилил

2019-01-15 16:39 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/CustomerRepositoryImplTest.java
> +        Assert.assertNotEquals(customer.getName(), customerOld.getName());
Update вообще переделал там сейчас по другому

2019-01-15 16:39 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/entity/TravelAgent.java
> +    private boolean enabled;
Boolean изменил

2019-01-15 16:45 UTC, aslanovr commented on src/main/java/com/javastudents/travelagency/service/impl/TravelAgentServiceImpl.java
> +public class TravelAgentServiceImpl implements TravelAgentService {
Реализовал

2019-01-15 16:46 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/CustomerRepositoryImplTest.java
> +        Assert.assertEquals(customerOld.getId(), customer.getId());
Переделал update

2019-01-15 18:26 UTC, RAsLM commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Integer tourScheduleIdExpected = 1;
сделано

2019-01-15 18:26 UTC, RAsLM commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Assert.assertEquals(id, purchaseRepository.read(id).getId());
Исправил

2019-01-15 18:26 UTC, RAsLM commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Assert.assertNotEquals(test, purchaseRepository.read(1).getOperationDate());
Исправил

2019-01-15 18:26 UTC, RAsLM commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Purchase transportSeat1 = purchaseRepository.read(id);
убрал

2019-01-15 18:26 UTC, RAsLM commented on src/test/java/com/javastudents/travelagency/repository/impl/PurchaseRepositoryImplTest.java
> +        Purchase purchase = Purchase.builder()
Убрал

2019-01-15 18:54 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/TourCategoryRepositoryImplTest.java
> +    }
переделал все update

2019-01-15 18:54 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/TourRepositoryImplTest.java
> +        String sql = "SELECT name from tour where tour_id = (select max(tour_id) from tour)";
Сделано

2019-01-15 18:54 UTC, aslanovr commented on src/test/java/com/javastudents/travelagency/repository/impl/TourRepositoryImplTest.java
> +        String tourName = "Test delete";
сделано

2019-01-21 15:22 UTC, merged